version: "3.5"
services:
  mysqldb:
    image: mysql

    restart: unless-stopped

    env_file: .env
    
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data

    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
  
  ping:
    environment:
      - NODE_ENV=development

    env_file: 
    - backend/.env
    - frontend/.env

    restart: on-failure

    build:
      context: .
      dockerfile: Dockerfile

    container_name: ping

    volumes: 
      - ./backend:/usr/api

    depends_on:
      mysqldb:
        condition: service_healthy

    stdin_open: true
    tty: true

    expose:
      - "3000"

    ports:
      - "3000:3000"

volumes:
  db-config:
  db-data: