version: "3"
services:
  mysqldb:
    image: mysql

    restart: unless-stopped

    env_file: strava-backend/.env
    
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
  
  ping-api:
    environment:
      - NODE_ENV=development

    env_file: strava-backend/.env

    build:
      context: .
      dockerfile: strava-backend/Dockerfile.dev

    container_name: ping-api

    volumes: 
      - ./strava-backend:/usr/api

    depends_on:
      - mysqldb

    stdin_open: true
    tty: true

    expose:
      - "3000"

    ports:
      - "3000:3000"

    command: npm run dev

  quasar:
    env_file: strava-frontend/.env

    build:
      context: .
      dockerfile: strava-frontend/Dockerfile
      target: 'develop-stage'

    depends_on:
      - ping-api

    ports:
    - '9000:9000'

    volumes:
    - '.:/usr/app'

    command: /bin/sh -c "yarn && quasar dev"

volumes:
  db-config:
  db-data: