version: "3"
services:
  mysqldb:
    image: mysql

    restart: unless-stopped

    env_file: ./.env
    
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
  ping-api:
    environment:
      - NODE_ENV=development

    env_file: ./.env

    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: ping-api

    volumes: 
      - .:/usr/api

    depends_on:
      - mysqldb

    stdin_open: true
    tty: true

    expose:
      - "3000"

    ports:
      - "3000:3000"

    command: npm run dev

volumes:
  db-config:
  db-data: